apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- route.yaml

commonLabels:
  app.kubernetes.io/part-of: http-server
  app.kubernetes.io/managed-by: kustomize