name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to the registry
      uses: redhat-actions/podman-login@9184318aae1ee5034fbfbacc0388acf12669171f # v1
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: quay.io
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/rcook/test:hello-world

    - name: Push the image
      run: docker push quay.io/rcook/test:hello-world

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.3.0
      with:
        cosign-release: 'v2.2.2'

    - name: authenticate to receive token and register it to use for signing
      run: |
        TOKEN=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
        -d "username=${{ secrets.AUTH_USER }}" \
        -d "password=${{ secrets.AUTH_PASSWORD }}" \
        -d "grant_type=password" \
        -d "scope=openid" \
        -d "client_id=sigstore" \
        ${{ secrets.OIDC_ISSUER_URL }}/protocol/openid-connect/token |  sed -E 's/.*"access_token":"([^"]*).*/\1/')
        echo "$TOKEN" >> $GITHUB_ENV

    - name: Sign the image using the token
      run: cosign sign -y --fulcio-url=${{ secrets.FULCIO_URL }} --rekor-url=${{ secrets.REKOR_URL }} --oidc-issuer=${{ secrets.OIDC_ISSUER_URL }} --identity-token=${{ env.TOKEN }} quay.io/rcook/test:hello-world